platform :ios, "8.0"

target "Merchant" do
  pod 'MMDrawerController', '~> 0.5'
  pod 'MagicalRecord', '2.2'
  pod 'CocoaLumberjack', '2.0.0-beta3'
  pod 'SocketRocket'
  pod 'ActionSheetPicker-3.0', '~> 1.3.1'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'SSKeychain', '~> 1.2'
  pod 'CoreBitcoin', '~> 0.5'
  pod 'PureLayout'
end
